import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ReactNode } from "react";

import "./globals.css";
import ConfirmProvider from "@/components/providers/ConfirmProvider";
import QueryProvider from "@/components/providers/QueryProvider";
import { Toaster } from "@/components/ui/sonner";

import AuthProvider from "../components/providers/AuthProvider";

interface Props {
  children: ReactNode;
}

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "pick your pick",
  description: "Generated by create next app",
};

export default function RootLayout(props: Props) {
  const { children } = props;
  return (
    <html lang="en">
      <body className={inter.className}>
        <ConfirmProvider>
          <AuthProvider>
            <>
              <QueryProvider>{children}</QueryProvider>
              <Toaster position="top-right" />
            </>
          </AuthProvider>
        </ConfirmProvider>
      </body>
    </html>
  );
}
