import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ReactNode } from "react";

import "./globals.css";
import QueryProvider from "@/components/provider/QueryProvider";
import { Toaster } from "@/components/ui/sonner";

import AuthProvider from "../components/provider/AuthProvider";

interface Props {
  children: ReactNode;
}

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "pick your pick",
  description: "Generated by create next app",
};

export default function RootLayout(props: Props) {
  const { children } = props;
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <QueryProvider>
            {children}
            <Toaster position="top-right" />
          </QueryProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
